/**
 * @file api/report.js
 * @description Standalone HTML report generator and download controller.
 */

const express = require('express');
const { verifyOtpToken } = require('../middleware/authGuard');

const router = express.Router();

function escapeHtml(str) {
  if (str === null || str === undefined) return '';
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

router.post('/download', verifyOtpToken, async (req, res) => {
  try {
    const { query = 'Target Record', content = 'No breach text provided' } = req.body || {};
    const safeQuery = escapeHtml(query);
    const safeContent = escapeHtml(content);

    const htmlReport = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>OSINT Breach Intelligence Report - ${safeQuery}</title>
  <style>
    body { background: #070A13; color: #e2e8f0; font-family: 'Courier New', Courier, monospace; padding: 40px 20px; margin: 0; }
    .card { background: #0B0F19; border: 1px solid #00F3FF; border-radius: 12px; padding: 28px; max-width: 860px; margin: 0 auto; box-shadow: 0 0 30px rgba(0, 243, 255, 0.2); }
    h1 { color: #00F3FF; margin-top: 0; font-size: 24px; letter-spacing: 1px; }
    .badge { display: inline-block; background: #FF003C; color: #fff; padding: 4px 12px; border-radius: 4px; font-weight: bold; font-size: 12px; letter-spacing: 1px; }
    .meta-row { display: flex; justify-content: space-between; flex-wrap: wrap; gap: 10px; margin: 16px 0; font-size: 13px; color: #94a3b8; border-bottom: 1px solid rgba(0, 243, 255, 0.2); padding-bottom: 12px; }
    pre { background: #030712; padding: 20px; border-radius: 8px; color: #00FF66; white-space: pre-wrap; font-size: 13px; border: 1px solid rgba(0, 243, 255, 0.2); line-height: 1.6; overflow-x: auto; }
    .footer { margin-top: 24px; font-size: 11px; color: #64748b; border-top: 1px solid rgba(255, 255, 255, 0.1); padding-top: 14px; text-align: center; }
  </style>
</head>
<body>
  <div class="card">
    <div style="display: flex; justify-content: space-between; align-items: center; flex-wrap: wrap; gap: 10px;">
      <h1>[ OSINT THREAT INTELLIGENCE REPORT ]</h1>
      <span class="badge">CONFIRMED EXPOSURE</span>
    </div>
    <div class="meta-row">
      <div>Target: <strong style="color: #00F3FF;">${safeQuery}</strong></div>
      <div>Security Classification: <strong style="color: #FF003C;">CRITICAL THREAT</strong></div>
      <div>Generated: <strong>${new Date().toUTCString()}</strong></div>
    </div>
    <h3 style="color: #00F3FF; margin-top: 20px;">[ Extracted Intelligence Records ]</h3>
    <pre>${safeContent}</pre>
    <div class="footer">Generated by OSINT-BreachShield Intelligence Platform • Confidential • Zero-Knowledge Verified</div>
  </div>
</body>
</html>`;

    res.setHeader('Content-Disposition', 'attachment; filename="breach_report.html"');
    res.setHeader('Content-Type', 'text/html; charset=utf-8');
    return res.send(htmlReport);
  } catch (err) {
    console.error('Download error:', err.message);
    res.status(500).json({ success: false, error: err.message });
  }
});

module.exports = router;
